sonarscan reusable workflow added
htec-infra/gha-tbd pull request #1
Opened 2021-12-02 14:22 UTC by ng-htec

readme added for sonarscan

2021-12-06 07:20 UTC, jz-htec requested changes

2021-12-06 07:20 UTC, jz-htec commented on sonarscan/sonar-scan-dotnet.yml
> +      - uses: actions/checkout@v2
GitHub token should be also utilized in checkout phase

2021-12-06 07:20 UTC, jz-htec commented on sonarscan/sonar-scan-dotnet.yml
> +      BUILD_DIR:
Default value should be project root directory

2021-12-07 15:51 UTC, jz-htec reviewed
Few more comments on the PR just to polish everything

2021-12-07 15:51 UTC, jz-htec commented on utils/action.yml
> +  repo_name:
Consider also to export other available variables, such as APP_VERSION, or APP_REVISION, etc.

2021-12-07 15:51 UTC, jz-htec commented on sonarscan/dotnet.yml
> +      SONAR_TOKEN:
I think it would be better to use lowercase secrets name to avoid confusion with ENVs

2021-12-08 07:31 UTC, ng-htec commented on sonarscan/dotnet.yml
> +      DOTNET_VERSION:
I have resolved that on previous commit https://github.com/htec-infra/gha-tbd/commit/53a1bb6abc72767b7d1205021b49b684230be992#diff-19e398a45e0b6d682d7c64cc29a699341d0f133fbbe711c5a5b78b72e812e775

2021-12-08 07:34 UTC, ng-htec commented on sonarscan/dotnet.yml
> +      SONAR_TOKEN:
Agree with you. It will be fixed on next push

2021-12-08 07:40 UTC, ng-htec commented on utils/action.yml
> +  repo_name:
Will be added on next push

2021-12-08 08:24 UTC, jz-htec approved these changes
Excellent!

2021-12-08 08:33 UTC, merged